name: Rails Tests and Lint

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Set up Database
        env:
          RAILS_ENV: test
        run: bin/rails db:prepare

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test:all
