name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.11"
          bundler-cache: true

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create secrets file
        run: |
          echo "KAMAL_REGISTRY_PASSWORD=${{ secrets.KAMAL_REGISTRY_PASSWORD }}" > .kamal/secrets
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> .kamal/secrets
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .kamal/secrets
          echo "OMNIAUTH_CLIENT_ID=${{ secrets.OMNIAUTH_CLIENT_ID }}" >> .kamal/secrets
          echo "OMNIAUTH_CLIENT_SECRET=${{ secrets.OMNIAUTH_CLIENT_SECRET }}" >> .kamal/secrets
          echo "ALERT_EMAIL_ADDRESS=${{ secrets.ALERT_EMAIL_ADDRESS }}" >> .kamal/secrets
          echo "MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}" >> .kamal/secrets
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .kamal/secrets

      - name: Deploy with Kamal
        run: bin/kamal deploy
